name: CI

on:
  push:
    branches:
      - main
      - develop
      - feat/**
  pull_request:
    branches:
      - main

jobs:
  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            apps/web/package-lock.json
      - name: Install landing dependencies
        run: npm ci
      - name: Install Next.js dependencies
        run: npm ci --prefix apps/web
      - name: Run Next.js lint
        run: npm run lint --prefix apps/web

  backend-checks:
    name: Backend Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: apps/api/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/api/requirements.txt
          pip install pytest
      - name: Compile sources
        run: python -m compileall apps/api/app
      - name: Run pytest
        working-directory: apps/api
        run: pytest --maxfail=1 --disable-warnings -q
